---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/posts
  label: Blog Posts
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
upload_dir: jeds_hut
public_path: https://res.cloudinary.com/jedn-web-dev/image/upload/t_basic_blog
front_matter_path: https://res.cloudinary.com/jedn-web-dev/image/upload
use_front_matter_path: true
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
